services:
  - type: web
    name: emergency-backend-maclin
    runtime: node
    plan: free
    # 1. Tell Render to install from the backend folder
    buildCommand: cd backend && npm install
    # 2. Tell Render to start the file inside the backend folder
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000